.gitignore, README.md, pose_est_nets/datasets/dali.py, pose_est_nets/datasets/datasets.py, pose_est_nets/losses/losses.py, pose_est_nets/models/regression_tracker.py, pose_est_nets/utils/fiftyone_plotting_utils.py, pose_est_nets/utils/heatmap_tracker_utils.py, pose_est_nets/utils/io.py, pose_est_nets/utils/plotting_utils.py, scripts/configs/data/data_params.yaml, scripts/configs/eval/eval_params.yaml, scripts/configs/losses/loss_params.yaml, scripts/configs/model/model_params.yaml, scripts/predict_compare.py, scripts/predict_new_vids.py, scripts/render_labeled_vids.py, scripts/train_hydra.py, scripts/visualize_frame_preds.py, tests/test_base_resnet.py, tests/test_regression_tracker.py
* refactored image plotting in fiftyone, now called `visualize_frame_preds.py`
* some fixes in `plotting_utils.py`
* a hydra script for predicting new vids `predict_new_vids.py`
* a hydra script for rendering vids based on csv predictions from multiple models `render_labeled_vids.py`
* style + explanation changes to `README.md`
* fixed some paths in tests
* making sure that the following works: full training -> prediction on train/test/val -> fiftyone -> prediction on new test vids
Open Issues:
* using actual keypoint names in `plotting_utils.py` - should we use a list of bp names to initialize the models themselves, instead of specifying an integer like `num_keypoints=17`?
* deciding on simple conventions like -- how should we name the saved csv, where do we want the labeled videos to be …
=> Video prediction

pose_est_nets/datasets/datasets.py, pose_est_nets/datasets/preprocessing.py, pose_est_nets/models/heatmap_tracker.py, pose_est_nets/models/regression_tracker.py, pose_est_nets/utils/fiftyone_plotting_utils.py, pose_est_nets/utils/plotting_utils.py, pose_est_nets/utils/wrappers.py, scripts/configs/data/data_params.yaml, tests/test_datamodules.py, tests/test_datasets.py, tests/test_heatmap.py, tests/test_regression_tracker.py, tests/test_subpixmaxima.py
Instead of returning batches as lists, return them as dicts so that access is cleaner
images = batch["images"]
instead of 
images = batch[0]
Data loaders now also return the image index
=> return batches as dicts

scripts/configs/eval/eval_params.yaml, scripts/create_fiftyone_dataset.py
add control so that eval.fiftyone.remote=False can be used as required
modified:   scripts/configs/eval/eval_params.yaml
modified:   scripts/create_fiftyone_dataset.py
=> add eval.fiftyone.remote

lightning_pose/utils/predictions.py
currently `predict_new_vids` will create a data loader if one is not passed, which is not really needed. this takes time to load the data and compute pca, especially for large datasets. the code now defaults to skipping automatic data loader creation for video inference.
=> [fix] accelerate inference setup by skipping pca computation

lightning_pose/utils/scripts.py, tests/data/test_utils.py
* generalize keypoint access from dataframes in compute_metrics (necessary if we want to compute metrics on eks outputs, which have an additional z-score column for each keypoint)
* ensure pca losses are not computed in compute_metrics if datamodule is not passed
* do not monitor validation loss if not performing early stopping - this is important if there is no validation dataset (which happens when testing the app on a small number of labeled frames)
* set torch seed for undo_affine_transform test; failed once with a weird seed (first time)
=> generalize keypoint access from dataframes in metrics

scripts/converters/dlc2lp.py
The conversion script was failing as it was detecting folders in the "labeled_frames" folder that did not contain any frame data.
Examples of such folders are hidden folders, such as .DS_Store folders that MacOS generates.
The other examples are folders created by DeepLabCut when running the `check_labels` function (folders where labels are plotted on top of the frames).
This is a simple fix to filter out the potential problematic folders.
There is maybe a better/safer approach by generating a list of videos (from the videos folder or the config.yaml file) and then looking for folders in the labeled_videos folder that are exact matches of the basenames.
=> ignore hidden "_labeled" folders in dlc to lp conversion

lightning_pose/apps/video_diagnostics.py
User saw an error before a video was selected; made a hotfix so that no computations are attempted until both
1) at least one model is selected
2) a video is selected
=> [fix] streamlit video page bugfix

lightning_pose/data/dali.py
Here is the corrected pull request with the variable passed to the correct function. 
(continued from here: https://github.com/danbider/lightning-pose/pull/179)
=> Passing vfr_check to fn.readers.video

lightning_pose/data/dali.py, lightning_pose/data/datamodules.py, lightning_pose/data/datasets.py, lightning_pose/data/utils.py
previously there was a single augmentation pipeline that was applied to train, val, and test data. This meant that validation metrics reported during training were affected by augmentations, and that early stopping was also dependent on augmentations. This PR solves this issue by applying whatever augmentation pipeline is requested by the user through the config file to the train data; the val and test data are only ever resized.
=> remove augmentations for val/test data

lightning_pose/train.py
This allows you to see what config was associated with a run in tensorboard. 
To access the new logged data, you have to go to the text tab. 
Screenshots:
=> Log hydra job config to tensorboard

lightning_pose/callbacks.py, lightning_pose/models/base.py, lightning_pose/models/heatmap_tracker_mhcrnn.py, lightning_pose/utils/scripts.py, tests/conftest.py, tests/test_callbacks.py
See lightning-ai/pytorch-lightning#20340 for the original issue. The implemented workaround no longer freezes/unfreezes layers via require_grad, instead we only modulate the learning rate of the backbone layer.
Unblocks #138
=> Change backbone finetuning strategy to allow for DDP

.github/workflows/run-tests.yml
The proposed continuous integration workflow runs tests for pull requests, and requires tests to pass before checking in to main (though this can be bypassed). We do not do any recurring builds or deployments.
There are three pieces needed to enable this workflow.
1. A branch protection rule (AKA Rules in repo settings).
2. A Github Action (this PR)
3. A GPU Runner (we need to first upgrade the paninski org to Teams tier).
I added a branch protection rule that requires tests to pass before merging a commit. This rule is disabled right now since the github action is not yet checked in. Please take a look at the settings:
https://github.com/paninski-lab/lightning-pose/settings/rules/2377592
Writers to this repository may bypass the rule - this setting is required to allow us to push to main …
=> Continuous integration using github actions

lightning_pose/utils/predictions.py, lightning_pose/utils/scripts.py, scripts/configs/config_default.yaml
I wanted to change the standard colormap for the labelled videos ("cool") is it is harder to differentiate keypoints when the number is larger. So I added the option to choose the colormap in the yaml file.
=> Added option to choose colormap for labelled videos

lightning_pose/losses/losses.py, lightning_pose/utils/pca.py, lightning_pose/utils/scripts.py, tests/utils/test_pca.py
Config:
losses.pca_singleview.centering_method = null | mean | median
=> Add PCA Centering method (experimental)

lightning_pose/data/datasets.py, lightning_pose/utils/scripts.py, tests/data/test_datasets.py
As an added bonus this should now work on windows paths. (prior, we were splitting on "/")
=> Context frames can use any delimiter

lightning_pose/__init__.py, scripts/configs/config_default.yaml, scripts/configs/config_mirror-mouse-example.yaml, tests/conftest.py, tests/test_train.py
Out of the box, train_hydra only works when run from the repo root. This was due to the use of relative paths. These are replaced with absolute paths and the config now adheres to the public spec.
Prevents issues like #195 from being encountered on the mirror mouse example.
Additionally tweaked the default config. If you don't change data_dir, it will error with 
`OSError: /replace/with/your/path is not a valid path`. Also `test_videos_directory` defaults to `data.video_dir.`
=> Replace relative paths with absolute paths in demo config

lightning_pose/data/datasets.py
Using `list[Path]` in type annotation is supported in python 3.10 but not 3.8 used by sphinx.
Doc build failure: https://readthedocs.org/projects/lightning-pose/builds/26240407/
Stack overflow: https://stackoverflow.com/a/75317316
=> Fix doc build failure

lightning_pose/train.py, tests/test_train.py
Gives memory of what labeled datapoints were used to train the model, for use in future features.
Additional changes
* Save files before training starts. This way they exist even if training prematurely dies.
* Use resolve=True flag of OmegaConf.save which will resolve ${vars} to their strings in the saved config.
=> Save copy of labeled data csv to output dir

docs/api/lightning_pose.models.backbones.vit_img_encoder.ImageEncoderViT.rst, docs/api/lightning_pose.models.base.BaseSupervisedTracker.rst, docs/api/lightning_pose.models.base.SemiSupervisedTrackerMixin.rst, docs/api/lightning_pose.models.heatmap_tracker_mhcrnn.SemiSupervisedHeatmapTrackerMHCRNN.rst, docs/api/lightning_pose.utils.cropzoom.generate_cropped_labeled_frames.rst, docs/api/lightning_pose.utils.cropzoom.generate_cropped_video.rst, docs/api/lightning_pose.utils.io.get_context_img_paths.rst, docs/api/lightning_pose.utils.io.load_label_csv_from_cfg.rst, docs/api/lightning_pose.utils.predictions.export_predictions_and_labeled_video.rst, docs/api/lightning_pose.utils.predictions.get_cfg_file.rst, docs/api/lightning_pose.utils.predictions.make_cmap.rst, docs/modules/lightning_pose.utils.rst, lightning_pose/data/datasets.py, lightning_pose/train.py, lightning_pose/utils/cropzoom.py, lightning_pose/utils/io.py, lightning_pose/utils/predictions.py, lightning_pose/utils/scripts.py, scripts/predict_new_vids.py, setup.py, tests/data/test_datasets.py, tests/test_train.py, tests/utils/test_cropzoom.py, tests/utils/test_io.py, tests/utils/test_predictions.py, tests/utils/test_scripts.py
It's a lot of diffs, 1. because I moved some things around.
* export_predictions_and_labeled_video method moved from scripts.py to predictions.py.
* get_context_img_paths moved to io.py
* regenerated api docs.
2. Because of the tests. I checked in some input files, and the cropzoom expected output files. This way we can visually see the cropping. If we make any intentional changes, all we have to do is copy the test output to the expected_model_output directory.
=> Save out detector artifacts on detector training

lightning_pose/utils/predictions.py
just a minor cleanup, tired of randomly finding folders with hundreds of log files scattered about my computer :)
=> get rid of unnecessary lightning logs during inference

lightning_pose/model.py, lightning_pose/utils/scripts.py, scripts/configs/config_default.yaml, scripts/configs/config_mirror-mouse-example.yaml, tests/conftest.py, tests/test_train.py
1. For csv_file prediction, change data_dir default from csv_file.parent to cfg.data.data_dir
2. Resolve csv_file to absolute path before prediction. Reason being that CLI deals with paths relative to current working directory, while downstream assumes csv_file is relative to data_dir. 
3. Update downstream code to be able to handle CSV file as absolute path.
=> Minor fixes

.gitignore, cli/main.py, docs/api/lightning_pose.utils.cropzoom.generate_cropped_csv_file.rst, docs/api/lightning_pose.utils.scripts.calculate_steps_per_epoch.rst, docs/api/lightning_pose.utils.scripts.calculate_train_batches.rst, docs/source/api.rst, docs/source/user_guide_advanced/cropzoom_pipeline.rst, docs/source/user_guide_advanced/index.rst, lightning_pose/__init__.py, lightning_pose/model.py, lightning_pose/train.py, lightning_pose/utils/cropzoom.py, lightning_pose/utils/scripts.py, tests/conftest.py, tests/fetch_test_data.py, tests/models/test_heatmap_tracker.py, tests/models/test_heatmap_tracker_mhcrnn.py, tests/models/test_regression_tracker.py, tests/test_train.py, tests/utils/test_cropzoom.py, tests/utils/test_predictions.py
I have refactored it so that there is no cropzoom in the core lightning_pose code. All cropzoom stuff is invoked externally using `litpose crop` and `litpose remap`.
Reasons for this:
- allow us to modify cropzoom things without risk of breaking core lightning pose code
- if something fails, we can re-run just that thing (instead of all of training, or all of prediction)
- train, predict, crop, remap commands can be farmed out to different kinds of machines using slurm or lightning jobs.
See docs: https://lightning-pose--250.org.readthedocs.build/en/250/source/user_guide_advanced/cropzoom_pipeline.html
=> Add support for cropzoom pipeline

docs/api/lightning_pose.callbacks.UnfreezeBackbone.rst, docs/source/user_guide/config_file.rst, docs/source/user_guide_advanced/custom_imgaug_pipeline.rst, docs/source/user_guide_advanced/index.rst, lightning_pose/data/augmentations.py, lightning_pose/data/datamodules.py, lightning_pose/data/datasets.py, lightning_pose/data/utils.py, lightning_pose/utils/scripts.py, tests/data/test_augmentations.py, tests/data/test_datamodules.py, tests/utils/test_scripts.py
The current imgaug code defines a handful of hard-coded pipelines that are defined by strings like "dlc", "dlc-top-down", etc. While succinct, this approach is not flexible and does not scale well.
To address this issue, I have refactored the imgaug code so that it can continue to use the previous string aliases (i.e. is backwards compatible), but also allows users to define their own custom pipeline in the config file.
Specifically:
- `lightning_pose.data.augmentations.imgaug_transform` is now a fully flexible core function that takes in a parameter dict and constructs an imgaug pipeline; the parameter dict defines the types of augmentations used, their various parameters, and their order. Unlike before, it does not rely on the bulky `cfg` DictConfig that specfies the entire Lightning …
=> imgaug refactor

cli/main.py, lightning_pose/model.py, lightning_pose/utils/io.py, lightning_pose/utils/scripts.py
1. The litpose remap command had a glaring bug where we were subtracting bboxes instead of adding. This only impacted salamander analysis. Chickadee used a custom script where this bug was not present.
2. When running litpose train on the same output directory twice, we currently save out checkpoints in directories like version_0, version_1, ... I thought I had disabled this incrementing a while ago with the `enable_version_counter` flag to ModelCheckpoint, but turns out that is a totally different feature. The relevant feature is actually TensorBoardLogger `version` flag: https://lightning.ai/docs/pytorch/stable/extensions/generated/lightning.pytorch.loggers.TensorBoardLogger.html#lightning.pytorch.loggers.TensorBoardLogger.params.version
So fix the io.py method that gets the checkpoint. …
=> Two small but important fixes

cli/commands/train.py, cli/main.py, lightning_pose/migrations/migrations.py, lightning_pose/migrations/rename_time_directories.py
Fixes #278 
Example output:
```
Fixing directory names (https://github.com/paninski-lab/lightning-pose/issues/278)...
Renamed: outputs/2025-03-31/15:55:58 -> outputs/2025-03-31/15-55-58
Renamed: outputs/2025-03-03/09:37:22 -> outputs/2025-03-03/09-37-22
Renamed: outputs/2025-03-03/09:44:04 -> outputs/2025-03-03/09-44-04
Renamed: outputs/2025-03-03/09:39:42 -> outputs/2025-03-03/09-39-42
Renamed: outputs/2025-03-03/09:47:41 -> outputs/2025-03-03/09-47-41
Renamed: outputs/2025-03-03/09:42:08 -> outputs/2025-03-03/09-42-08
Renamed: outputs/2025-03-03/09:57:56 -> outputs/2025-03-03/09-57-56
Renamed: outputs/2025-03-03/14:57:13 -> outputs/2025-03-03/14-57-13
Renamed: outputs/2025-03-03/14:49:46 -> outputs/2025-03-03/14-49-46
Renamed: outputs/2025-03-03/15:34:01 -> outputs/2025-03-03/15-34-01 …
```
=> Replace : with - in default model directory

lightning_pose/data/augmentations.py, tests/utils/test_scripts.py
Fix to a pretty serious bug in the `dlc-lr` and `dlc-top-down` image augmentation pipelines - I was erroneously flipping the images/keypoints rather than rotating them. 
For example, imagine a top-down view of an animal that is pointing towards the top of the frame, with the center vertical axis of the frame running down the axis of the animal. If the left/right ears are labeled as such, flipping over the vertical axis would result in an animal that looks almost the same, but the left/right ear keypoints are now on the wrong side of the head.
Instead of flipping images we should be rotating them.
=> bug fix in left-right/top-down augmentation pipeline

.flake8, docs/api/lightning_pose.models.backbones.vit_mae.ViTVisionEncoder.rst, docs/api/lightning_pose.models.backbones.vit_sam.load_sam_vision_encoder_hf.rst, docs/modules/lightning_pose.models.backbones.rst, lightning_pose/models/backbones/__init__.py, lightning_pose/models/backbones/vit_mae.py, lightning_pose/models/backbones/vit_sam.py, lightning_pose/models/backbones/vits.py, lightning_pose/models/base.py, lightning_pose/utils/scripts.py, pyproject.toml, scripts/configs/config_default.yaml, tests/models/test_base.py
The LP repo currently only supports the Segment Anything ViT backbone; this PR introduces another backbone (still vit-b/16) but pretrained on imagenet using a masked autoencoding loss (from HuggingFace). This PR opens the door to using our own pretrained ViT models.
=> new backbone: ViT pretrained on imagenet with mae loss

scripts/predict_new_vids.py
The predict_new_vids.py script still had `save_heatmaps` as a parameter in its call to `export_predictions_and_labeled_video` which was removed in https://github.com/paninski-lab/lightning-pose/commit/8b980a63b795fae077b7736b82c16843c826d821
These scripts are probably not really useful in the future (?). But I still use the hydra approach for running multiple models (via slurm and submitit) as well as running multiple models on a directory of videos (to use EKS later). This is still not possible with the CLI (if I am not mistaken).
=> Remove unexpected save_heatmaps parameter predict_new_vids.py

lightning_pose/apps/labeled_frame_diagnostics.py, lightning_pose/apps/plots.py, scripts/predict_new_vids.py
For downstream applications (such as KeypointMoseq) the confidence/likelihood of each prediction are important. 
litpose models often seem to be "over confident" in their predictions. I found myself comparing the models with calibration curves. I tried adding it to the app and it looks okay. 
Here is an example comparing a few models. Not sure if this is useful, let me know.
=> Calibration plot for frame diagnostics streamlit
